### ISSUE TITLE
re-create verifier issue

### ISSUE THREAD

**Issue by martbhell** [CSCfi/ansible-role-rally-scenarios#32]
If someone runs "rally delete-verifier" and then runs this role to re-create the verifier, then the below ansible task will not execute because of the conditional - and they did not delete the tempest_config.

--------------

https://github.com/CSCfi/ansible-role-rally-scenarios/blob/master/tasks/tempest_verifiers.yml#L82

```
  - name: Configure rally verifier if templating in the temp**l**est config file task changed
    shell: "source /home/rally/rally/bin/activate && rally deployment use {{ item.key }} &>/dev/null && rally verify use-verifier --id {{ item.key }} &&  rally verify configure-verifier --extend /home/rally/tempest_configs/{{ item.key }}.tempest && deactivate"
    args:
      executable: /bin/bash
    when: reg_tempest_config.changed
```

Probably what we want to do here is to add an OR statement to the above task, maybe something like:

```
    when: reg_tempest_config.changed or verifiers.changed
```
